config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'
  get '/recipes/search', to: 'recipes#search'
  get 'recipes', to: 'recipes#index'
  get 'recipes/:id', to: 'recipes#show', as: 'recipe'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    def search
        query = params[:query]
        results = RecipeService.search(query)
        render json: results
    end
    def index
        query = params[:query]
        @recipes = query.present? ? RecipeService.search(query) : []
    end
    def show
        recipe_id = params[:id]
        @recipe = RecipeService.fetch_recipe(recipe_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeFinder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<div class="recipes">
  <%= form_with url: recipes_path, method: :get do |form| %>
    <%= form.text_field :query, placeholder: "Enter a recipe" %>
    <%= form.submit "Search" %>
  <% end %>
  <% if @recipes.present? %>
    <% @recipes.each do |recipe| %>
      <div class="recipe-card">
      <h2><%= link_to recipe["title"], recipe_path(recipe["id"]) %></h2>
        <img src="<%= recipe["image"] %>" alt="<%= recipe["title"] %>">
      </div>
    <% end %>
  <% else %>
    <p>No recipes found.</p>
  <% end %>
</div>

app/views/recipes/show.html.erb
<% if @recipe %>
  <h1><%= @recipe["title"] || "No title available" %></h1>
  <img src="<%= @recipe["image"] || "default-image.jpg" %>" alt="<%= @recipe["title"] || "No title available" %>">
  <p>Instructions: <%= raw @recipe["instructions"] || "No instructions available" %></p>
<% else %>
  <p>No recipe found.</p>
<% end %>